spring:
  rabbitmq:
    host: localhost
    port: 5672
  datasource:
    url: jdbc:postgresql://localhost:5432/workshop
    username: workshop
    password: workshop
    driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      bindings:
        input:
          consumer:
            max-attempts: 1
          destination: workshop.input
          group: group
        output:
          destination: workshop.output
      rabbit:
        bindings:
          input:
            consumer:
              declareExchange: true
              missing-queues-fatal: true
              autoBindDlq: true
              declareDlx: true
              dlqDeadLetterExchange:
              dlqTtl: 10000
          output:
            producer:
              declareExchange: true

application:
  exceptions:
    UnmarshallingFailureException