spring:
  cloud:
    stream:
      bindings:
        input:
          consumer:
            max-attempts: 1
          destination: workshop.input
          group: group
        output:
          destination: workshop.output
      rabbit:
        bindings:
          input:
            consumer:
              missing-queues-fatal: true
              autoBindDlq: true
              declareDlx: true
              dlqDeadLetterExchange:
              dlqTtl: 10000
          output:
            producer:
              declareExchange: true
  jpa:
    hibernate:
      ddl-auto: create-drop
application:
  exceptions:
    UnmarshallingFailureException